-- NOTE
-- doesn't work using postgreSQL
insert into Task (title, description, completed) values ('Rocket Science', 'A bright and zesty dressing perfect for salads and tacos.', true);
insert into Task (title, description, completed) values ('Control Room', 'Crispy sweet potato bites, delicious as a side or snack.', true);
insert into Task (title, description, completed) values ('Stockholm, Pennsylvania', 'Just add water for a hearty cheese and broccoli soup in minutes.', false);
insert into Task (title, description, completed) values ('Mo'' Money', 'A crunchy blend of nuts and pretzels with a spicy kick.', true);
insert into Task (title, description, completed) values ('WarGames: The Dead Code', 'Spicy black bean burgers, great on the grill.', true);
insert into Task (title, description, completed) values ('Smooth Talk', 'Creamy risotto made with mushrooms and herbs, perfect as a side dish or main course.', false);
insert into Task (title, description, completed) values ('Mouse on the Moon, The', 'Energy-efficient LED bulbs that can be controlled via smartphone.', false);
insert into Task (title, description, completed) values ('Olsen Gang, The (Olsen-Banden)', 'Fresh pre-cut carrot and celery sticks for easy snacking.', true);
insert into Task (title, description, completed) values ('Screamers', 'Crunchy granola with almonds and a hint of vanilla, perfect for breakfast.', false);
insert into Task (title, description, completed) values ('Two Women (Ciociara, La)', 'Compact ice maker for creating ice at home or in offices.', true);
insert into Task (title, description, completed) values ('Hitcher, The', 'Nutty and wholesome brown rice.', true);
insert into Task (title, description, completed) values ('In the Name of the King 2: Two Worlds', 'Gentle grooming gloves for shedding pets.', false);
insert into Task (title, description, completed) values ('Ursul', 'Countertop dishwasher for small kitchens.', true);
insert into Task (title, description, completed) values ('Breathing Fire', 'Gluten-free pasta made from red lentils, packed with protein.', false);
insert into Task (title, description, completed) values ('Romero', 'Eco-friendly bamboo holder for toothbrushes.', false);
insert into Task (title, description, completed) values ('Snow White', 'A nutritious shake with rich chocolate and refreshing mint flavors.', false);
insert into Task (title, description, completed) values ('I Married a Monster from Outer Space', 'Spicy black bean burgers, great on the grill.', true);
insert into Task (title, description, completed) values ('Major League', 'Delicious cookies made with almond flour for a gluten-free treat.', true);
insert into Task (title, description, completed) values ('Lolita', 'Creamy ice cream with a warm cinnamon flavor, perfect for dessert.', true);
insert into Task (title, description, completed) values ('Marriage Italian Style (Matrimonio all''italiana)', 'Delicious ravioli filled with creamy ricotta and fresh spinach.', true);
insert into Task (title, description, completed) values ('Black Nativity', 'A savory marinade for meats, perfect for grilling.', false);
insert into Task (title, description, completed) values ('Last Days, The', 'Fluffy pancakes with buttermilk flavor.', false);
insert into Task (title, description, completed) values ('City of Pirates (La ville des pirates) ', 'Comfortable pet carrier for travel and vet visits.', false);
insert into Task (title, description, completed) values ('Spanglish', 'Fresh seedless red grapes, perfect for snacking.', false);
insert into Task (title, description, completed) values ('Carmen Miranda: Bananas Is My Business', 'Breathable mesh sports leggings for ultimate comfort.', true);
insert into Task (title, description, completed) values ('Heartbreakers', 'A crunchy blend of nuts and pretzels with a spicy kick.', true);
insert into Task (title, description, completed) values ('$ (Dollars)', 'Quick boiling kettle for small kitchens and dorms.', false);
insert into Task (title, description, completed) values ('Who Killed the Electric Car?', 'Fluffy pancakes with buttermilk flavor.', false);
insert into Task (title, description, completed) values ('Alvin and the Chipmunks', 'A fashion-forward bomber jacket to elevate your casual looks.', true);
insert into Task (title, description, completed) values ('New Leaf, A', 'Creamy and crumbly cheese for salads and dishes.', true);
insert into Task (title, description, completed) values ('Clap, You''re Dead', 'Delicious noodles tossed in a sesamegarlic sauce.', true);
insert into Task (title, description, completed) values ('Days and Nights in the Forest (Aranyer Din Ratri)', 'Ceramic incense holder for a calming atmosphere.', true);
insert into Task (title, description, completed) values ('Parisian Love', 'Versatile canned black beans, ready to add to any dish.', true);
insert into Task (title, description, completed) values ('Joni''s Promise', 'Savory popcorn flavored with maple syrup and bacon bits.', false);
insert into Task (title, description, completed) values ('Avenging Angelo', 'Light and crispy baked chips, a healthier snack option.', false);
insert into Task (title, description, completed) values ('My Left Foot', 'Stylish ankle strap heels for a classy look at any event.', false);
insert into Task (title, description, completed) values ('Boys from Brazil, The', 'Tripod with wireless remote for effortless photo-taking.', false);
insert into Task (title, description, completed) values ('New Guy, The', 'Professional-grade nail care set for manicures and pedicures.', true);
insert into Task (title, description, completed) values ('Philomena', 'Crispy chips made from assorted garden vegetables, lightly salted.', true);
insert into Task (title, description, completed) values ('English Patient, The', 'Chic high-waisted skirt, perfect for professional or casual settings.', true);
insert into Task (title, description, completed) values ('Dans la peau d''une grande', 'A crunchy blend of nuts and pretzels with a spicy kick.', true);
insert into Task (title, description, completed) values ('Joan of Arc', 'Handheld vacuum cleaner for quick and easy cleaning.', false);
insert into Task (title, description, completed) values ('Mortuary', 'Bell peppers stuffed with rice, beans, and spices, ready to bake.', false);
insert into Task (title, description, completed) values ('Megiddo: The Omega Code 2', 'High-quality matcha for making traditional tea or lattes.', false);
insert into Task (title, description, completed) values ('Four Ways Out', 'Challenging puzzle game set for family entertainment.', false);
insert into Task (title, description, completed) values ('Lake House, The', 'Challenging puzzle game set for family entertainment.', false);
insert into Task (title, description, completed) values ('And When Did You Last See Your Father?', 'Easy mix for making spicy beef tacos.', true);
insert into Task (title, description, completed) values ('Green Fire', 'Mixed fresh vegetables for stir-frying or roasting.', true);
insert into Task (title, description, completed) values ('Rookie, The', 'Lightly salted rice cakes, perfect for a healthy snack.', true);
insert into Task (title, description, completed) values ('Drones', 'Comfortable wireless headphones designed for sleeping.', true);
